body:
  - type: textarea
    attributes:
      label: Describe the feature you'd like
      description: A clear and concise description of what you want to happen
    validations:
      required: true
