name: Report an issue
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Browser
      description: In which browser(s) did you encounter the issue?
      options:
        - label: Chrome
        - label: Firefox
    validations:
      required: true
  - type: input
    attributes:
      label: Extension version
      description: What version of the extension are you using?
      placeholder: 1.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: Redmine version
      description: What version of Redmine are you using?
      placeholder: 5.1.2.stable
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context / Screenshots
      description: Add any other context about the problem here. If applicable, add screenshots to help explain your problem.
      placeholder: Add other context here (e.g. screenshots, logs, etc.)
    validations:
      required: false
