/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TimersRouteImport } from "./routes/timers"
import { Route as TimeRouteImport } from "./routes/time"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as IssuesRouteImport } from "./routes/issues"
import { Route as IndexRouteImport } from "./routes/index"

const TimersRoute = TimersRouteImport.update({
  id: "/timers",
  path: "/timers",
  getParentRoute: () => rootRouteImport,
} as any)
const TimeRoute = TimeRouteImport.update({
  id: "/time",
  path: "/time",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: "/issues",
  path: "/issues",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/issues": typeof IssuesRoute
  "/settings": typeof SettingsRoute
  "/time": typeof TimeRoute
  "/timers": typeof TimersRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/issues": typeof IssuesRoute
  "/settings": typeof SettingsRoute
  "/time": typeof TimeRoute
  "/timers": typeof TimersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/issues": typeof IssuesRoute
  "/settings": typeof SettingsRoute
  "/time": typeof TimeRoute
  "/timers": typeof TimersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/issues" | "/settings" | "/time" | "/timers"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/issues" | "/settings" | "/time" | "/timers"
  id: "__root__" | "/" | "/issues" | "/settings" | "/time" | "/timers"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IssuesRoute: typeof IssuesRoute
  SettingsRoute: typeof SettingsRoute
  TimeRoute: typeof TimeRoute
  TimersRoute: typeof TimersRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/timers": {
      id: "/timers"
      path: "/timers"
      fullPath: "/timers"
      preLoaderRoute: typeof TimersRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/time": {
      id: "/time"
      path: "/time"
      fullPath: "/time"
      preLoaderRoute: typeof TimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/issues": {
      id: "/issues"
      path: "/issues"
      fullPath: "/issues"
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IssuesRoute: IssuesRoute,
  SettingsRoute: SettingsRoute,
  TimeRoute: TimeRoute,
  TimersRoute: TimersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
