name: Lint

on:
  pull_request: null

permissions: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      statuses: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: super-linter
        uses: super-linter/super-linter/slim@v8.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
