---
name: Publish Release

on:
  release:
    types:
      - released

permissions: {}

jobs:
  publish-chrome:
    name: Publish to Chrome Web Store
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - run: pnpm install --frozen-lockfile

      - run: pnpm run build:chrome:release

      - run: gh release upload "${RELEASE_TAG}" "$(ls .output/*-chrome.zip)"
        env:
          GITHUB_TOKEN: ${{ github.token }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}

      - run: |
          pnpm wxt submit \
            --chrome-zip .output/*-chrome.zip
        env:
          CHROME_EXTENSION_ID: ldcanhhkffokndenejhafhlkapflgcjg
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}

  publish-firefox:
    name: Publish to Firefox Addon Store
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - run: pnpm install --frozen-lockfile

      - run: pnpm run build:firefox:release

      - run: gh release upload "${RELEASE_TAG}" "$(ls .output/*-firefox.zip)"
        env:
          GITHUB_TOKEN: ${{ github.token }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}

      - run: |
          pnpm wxt submit \
            --firefox-zip .output/*-firefox.zip \
            --firefox-sources-zip .output/*-sources.zip
        env:
          FIREFOX_EXTENSION_ID: 2867093
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
