name: Publish

on:
  release:
    types:
      - released

permissions:
  contents: write

jobs:
  publish-chrome:
    name: Publish to Chrome Web Store
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - run: pnpm install --frozen-lockfile

      - run: pnpm run zip:chrome

      - run: gh release upload ${{ github.event.release.tag_name }} $(ls .output/*-chrome.zip)
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
      - run: pnpm wxt submit --chrome-zip .output/*-chrome.zip
        env:
          CHROME_EXTENSION_ID: ldcanhhkffokndenejhafhlkapflgcjg
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}

  publish-firefox:
    name: Publish to Firefox Addon Store
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - run: pnpm install --frozen-lockfile

      - run: pnpm run zip:firefox

      - run: gh release upload ${{ github.event.release.tag_name }} $(ls .output/*-firefox.zip)
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}

      - run: pnpm wxt submit --firefox-zip .output/*-firefox.zip --firefox-sources-zip .output/*-sources.zip
        env:
          FIREFOX_EXTENSION_ID: "{ea2ad5bc-e458-414d-8565-5cfe9f7cf0c2}"
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
